jaffle_shop:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: fbfaove-wl12411

      # User/password auth
      user: andrews
      password: progrSF<>03

      role: accountadmin
      database: dbt_test
      warehouse: pc_dbt_wh
      schema: main
      threads: 1
      client_session_keep_alive: False
      query_tag: dbt_as_test

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false (available v1.4+)